from typing import Dict, Any, List

def _get_base_template(color_theme: str, header_title: str, content_html: str) -> str:
    """
    Standard responsive base template wrapper with modern premium styling.
    """
    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{header_title}</title>
    <style>
        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, Arial, sans-serif;
            background-color: #F8FAFC;
            color: #1E293B;
            margin: 0;
            padding: 0;
            -webkit-font-smoothing: antialiased;
        }}
        .wrapper {{
            width: 100%;
            table-layout: fixed;
            background-color: #F8FAFC;
            padding: 40px 0;
        }}
        .container {{
            max-width: 600px;
            margin: 0 auto;
            background-color: #FFFFFF;
            border-radius: 16px;
            border: 1px solid #E2E8F0;
            box-shadow: 0 4px 12px rgba(15, 23, 42, 0.03);
            overflow: hidden;
        }}
        .header {{
            background: {color_theme};
            padding: 30px;
            text-align: center;
            color: #FFFFFF;
        }}
        .header h1 {{
            margin: 0;
            font-size: 24px;
            font-weight: 700;
            letter-spacing: -0.02em;
        }}
        .content {{
            padding: 30px;
        }}
        .meta-table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background-color: #F8FAFC;
            border-radius: 12px;
            overflow: hidden;
        }}
        .meta-table td {{
            padding: 12px 16px;
            border-bottom: 1px solid #E2E8F0;
            font-size: 14px;
        }}
        .meta-table td.label {{
            font-weight: 600;
            color: #475569;
            width: 35%;
        }}
        .meta-table td.value {{
            color: #0F172A;
            font-weight: 500;
        }}
        .card {{
            border-radius: 12px;
            padding: 20px;
            margin-bottom: 20px;
            border: 1px solid #E2E8F0;
        }}
        .card-green {{
            background-color: #ECFDF5;
            border-color: #A7F3D0;
        }}
        .card-orange {{
            background-color: #FFFBEB;
            border-color: #FDE68A;
        }}
        .card-red {{
            background-color: #FEF2F2;
            border-color: #FEE2E2;
        }}
        .card-blue {{
            background-color: #EFF6FF;
            border-color: #BFDBFE;
        }}
        .card-title {{
            font-size: 16px;
            font-weight: 700;
            margin-top: 0;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
        }}
        .section-title {{
            font-size: 16px;
            font-weight: 600;
            color: #0F172A;
            margin-top: 24px;
            margin-bottom: 12px;
            border-left: 4px solid #C9A84C;
            padding-left: 10px;
        }}
        .button {{
            display: inline-block;
            background-color: #C9A84C;
            color: #FFFFFF !important;
            text-decoration: none;
            padding: 12px 24px;
            border-radius: 8px;
            font-weight: 600;
            font-size: 14px;
            text-align: center;
            margin-top: 15px;
            box-shadow: 0 4px 6px rgba(201, 168, 76, 0.2);
        }}
        .footer {{
            background-color: #0F172A;
            padding: 24px;
            text-align: center;
            color: #94A3B8;
            font-size: 12px;
        }}
        .evidence-list {{
            margin: 0;
            padding-left: 20px;
            font-size: 13.5px;
            color: #334155;
        }}
        .evidence-list li {{
            margin-bottom: 6px;
        }}
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="container">
            <div class="header">
                <h1>{header_title}</h1>
            </div>
            <div class="content">
                {content_html}
            </div>
            <div class="footer">
                <p>This is an automated alert generated by TenderAI Intelligence Agent Platform.</p>
                <p>&copy; 2026 TenderIQ Inc. All rights reserved.</p>
            </div>
        </div>
    </div>
</body>
</html>
"""

def render_high_match_email(
    company_name: str,
    tender: Dict[str, Any],
    score: int,
    eligibility_verdict: str,
    why_matches: str,
    recommended_action: str,
    evidence: List[str]
) -> str:
    color_theme = "linear-gradient(135deg, #10B981 0%, #059669 100%)"
    header_title = f"🚀 High-Match Opportunity Found ({score}/100)"
    
    evidence_items = "".join(f"<li>{ev}</li>" for ev in evidence)
    
    content = f"""
    <p>Dear {company_name} Team,</p>
    <p>We have detected a highly matching government tender opportunity that perfectly aligns with your company profile capabilities.</p>
    
    <div class="card card-green">
        <h3 class="card-title" style="color: #065F46;">🌟 Match Summary</h3>
        <p style="margin: 5px 0; font-size: 14px; color: #065F46;"><strong>Opportunity Suitability Score:</strong> {score}/100</p>
        <p style="margin: 5px 0; font-size: 14px; color: #065F46;"><strong>Eligibility Verdict:</strong> {(eligibility_verdict or 'N/A').upper()}</p>
    </div>

    <div class="section-title">Tender Details</div>
    <table class="meta-table">
        <tr>
            <td class="label">Tender Title</td>
            <td class="value">{tender.get('title') or 'N/A'}</td>
        </tr>
        <tr>
            <td class="label">Department</td>
            <td class="value">{tender.get('department') or 'Not specified'}</td>
        </tr>
        <tr>
            <td class="label">Location</td>
            <td class="value">{tender.get('location') or 'Not specified'}</td>
        </tr>
        <tr>
            <td class="label">Budget</td>
            <td class="value">₹{f"{tender.get('budget'):,.2f}" if tender.get('budget') else 'Not specified'}</td>        </tr>
        <tr>
            <td class="label">Deadline</td>
            <td class="value">{tender.get('deadline') or 'Not specified'}</td>
        </tr>
    </table>

    <div class="section-title">Deterministic Alignment Evidence</div>
    <ul class="evidence-list">
        {evidence_items or "<li>Deterministic profile validation complete.</li>"}
    </ul>

    <div class="section-title">AI Matching Insights</div>
    <p style="font-size: 14.5px; line-height: 1.6; color: #334155;">{why_matches}</p>

    <div class="section-title">Recommended Bid Actions</div>
    <p style="font-size: 14.5px; line-height: 1.6; color: #334155;">{recommended_action}</p>

    <div style="text-align: center; margin-top: 30px;">
        <a href="http://localhost:5173" class="button">Go to TenderAI Dashboard</a>
    </div>
    """
    return _get_base_template(color_theme, header_title, content)

def render_medium_match_email(
    company_name: str,
    tender: Dict[str, Any],
    score: int,
    eligibility_verdict: str,
    why_matches: str,
    recommended_action: str,
    evidence: List[str]
) -> str:
    color_theme = "linear-gradient(135deg, #F59E0B 0%, #D97706 100%)"
    header_title = f"📋 Tender Requires Review ({score}/100)"
    
    evidence_items = "".join(f"<li>{ev}</li>" for ev in evidence)
    
    content = f"""
    <p>Dear {company_name} Team,</p>
    <p>A new tender opportunity has been analyzed and classified as a moderate match, requiring manual bid review.</p>
    
    <div class="card card-orange">
        <h3 class="card-title" style="color: #92400E;">🔍 Evaluation Stats</h3>
        <p style="margin: 5px 0; font-size: 14px; color: #92400E;"><strong>Opportunity Score:</strong> {score}/100</p>
        <p style="margin: 5px 0; font-size: 14px; color: #92400E;"><strong>Eligibility Verdict:</strong> {(eligibility_verdict or 'N/A').upper()}</p>
    </div>

    <div class="section-title">Tender Details</div>
    <table class="meta-table">
        <tr>
            <td class="label">Tender Title</td>
            <td class="value">{tender.get('title') or 'N/A'}</td>
        </tr>
        <tr>
            <td class="label">Department</td>
            <td class="value">{tender.get('department') or 'Not specified'}</td>
        </tr>
        <tr>
            <td class="label">Budget</td>
            <td class="value">₹{tender.get('budget'):,.2f}</td>
        </tr>
        <tr>
            <td class="label">Deadline</td>
            <td class="value">{tender.get('deadline') or 'Not specified'}</td>
        </tr>
    </table>

    <div class="section-title">Score Breakdown & Matching Points</div>
    <ul class="evidence-list">
        {evidence_items or "<li>Score calculated based on standard category matching.</li>"}
    </ul>

    <div class="section-title">AI Recommendation Summary</div>
    <p style="font-size: 14.5px; line-height: 1.6; color: #334155;">{why_matches}</p>
    
    <div class="section-title">Suggested Pursuit Action</div>
    <p style="font-size: 14.5px; line-height: 1.6; color: #334155;">{recommended_action}</p>

    <div style="text-align: center; margin-top: 30px;">
        <a href="http://localhost:5173" class="button">Review Score Details</a>
    </div>
    """
    return _get_base_template(color_theme, header_title, content)

def render_risk_email(
    company_name: str,
    tender: Dict[str, Any],
    priority: str,
    risk_summary: str,
    recommended_mitigation: str,
    evidence: List[str]
) -> str:
    # Use dark red gradient for CRITICAL risk
    is_critical = priority.upper() == "CRITICAL"
    color_theme = "linear-gradient(135deg, #7F1D1D 0%, #EF4444 100%)" if is_critical else "linear-gradient(135deg, #DC2626 0%, #B91C1C 100%)"
    header_title = f"🚨 CRITICAL Tender Risk Alert" if is_critical else "🚨 Tender Risk Alert"
    
    evidence_items = "".join(f"<li>{ev}</li>" for ev in evidence)
    
    content = f"""
    <p>Dear {company_name} Team,</p>
    <p>Our intelligent analyzer has detected significant eligibility, financial, or compliance risks for the following tender.</p>
    
    <div class="card card-red" style="border-width: { '2px' if is_critical else '1px' };">
        <h3 class="card-title" style="color: #991B1B;">⚠️ Risk Level: {priority.upper()}</h3>
        <p style="margin: 5px 0; font-size: 14.5px; color: #991B1B;"><strong>Critical gaps were identified in your profile match. Pursuing this tender might result in technical disqualification without mitigation.</strong></p>
    </div>

    <div class="section-title">Tender Details</div>
    <table class="meta-table">
        <tr>
            <td class="label">Tender Title</td>
            <td class="value">{tender.get('title') or 'N/A'}</td>
        </tr>
        <tr>
            <td class="label">Department</td>
            <td class="value">{tender.get('department') or 'Not specified'}</td>
        </tr>
        <tr>
            <td class="label">Budget</td>
            <td class="value">₹{tender.get('budget'):,.2f}</td>
        </tr>
    </table>

    <div class="section-title">Identified Gaps (Deterministic Gaps)</div>
    <ul class="evidence-list" style="color: #991B1B; font-weight: 500;">
        {evidence_items or "<li>A gap in certifications or financials was identified.</li>"}
    </ul>

    <div class="section-title">Risk Analysis Summary</div>
    <p style="font-size: 14.5px; line-height: 1.6; color: #334155;">{risk_summary}</p>
    
    <div class="section-title">Recommended Mitigations</div>
    <p style="font-size: 14.5px; line-height: 1.6; color: #334155;">{recommended_mitigation}</p>

    <div style="text-align: center; margin-top: 30px;">
        <a href="http://localhost:5173" class="button" style="background-color: #DC2626; box-shadow: 0 4px 6px rgba(220, 38, 38, 0.2);">Inspect compliance checklist</a>
    </div>
    """
    return _get_base_template(color_theme, header_title, content)

def render_deadline_email(
    company_name: str,
    tender: Dict[str, Any],
    days_remaining: int,
    submission_checklist: List[str]
) -> str:
    color_theme = "linear-gradient(135deg, #2563EB 0%, #1D4ED8 100%)"
    header_title = f"⏰ Tender Deadline Approaching ({days_remaining} Days Left)"
    
    checklist_items = "".join(f"<li>{item}</li>" for item in submission_checklist[:6])
    
    content = f"""
    <p>Dear {company_name} Team,</p>
    <p>This is a high-priority reminder that the submission window for the following tender is closing shortly.</p>
    
    <div class="card card-blue">
        <h3 class="card-title" style="color: #1E40AF;">⏳ Time Remaining</h3>
        <p style="margin: 5px 0; font-size: 16px; color: #1E40AF; font-weight: bold;">{days_remaining} calendar days left to submit response.</p>
        <p style="margin: 5px 0; font-size: 13px; color: #1E40AF;">Submission deadline: {tender.get('deadline')}</p>
    </div>

    <div class="section-title">Tender Details</div>
    <table class="meta-table">
        <tr>
            <td class="label">Tender Title</td>
            <td class="value">{tender.get('title') or 'N/A'}</td>
        </tr>
        <tr>
            <td class="label">Department</td>
            <td class="value">{tender.get('department') or 'Not specified'}</td>
        </tr>
    </table>

    <div class="section-title">Submission Document Checklist</div>
    <ul class="evidence-list">
        {checklist_items or "<li>Refer to the dashboard checklist for registration documents.</li>"}
    </ul>

    <div class="section-title">Submission Instructions</div>
    <p style="font-size: 14.5px; line-height: 1.6; color: #334155;">
        Please ensure all documents above are digitally signed, uploaded, and the tender fees/EMD deposits are completed.
        Avoid last-hour portal load issues by submitting at least 24 hours prior to the close.
    </p>

    <div style="text-align: center; margin-top: 30px;">
        <a href="http://localhost:5173" class="button" style="background-color: #2563EB; box-shadow: 0 4px 6px rgba(37, 99, 235, 0.2);">View Submission Workspace</a>
    </div>
    """
    return _get_base_template(color_theme, header_title, content)
